services:
  postgres:
    image: postgres:17
    container_name: ai_chatbot_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_password
      POSTGRES_DB: chatbot_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: