"""add username and date of birth to users

Revision ID: 1b9eb0d323f2
Revises: 8d0db4c2405d
Create Date: 2026-07-30 00:27:46.535324

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b9eb0d323f2'
down_revision: Union[str, Sequence[str], None] = '8d0db4c2405d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
